version: '3'
services:
  backend:
    image: boussad1ait/quotes_backend:v2
    ports:
      - "5000:5000"
    container_name: quotes-backend
    restart: unless-stopped
    networks:
      - quotes-app-network

  frontend:
    image: boussad1ait/quotes_frontend:v2
    ports:
      - "3000:3000"
    container_name: quotes-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - quotes-app-network

networks:
  quotes-app-network:
    driver: bridge